### ISSUE TITLE
v1.0.0 Release Checklist

### ISSUE THREAD

**Issue by craigbranscom** [Telos-Foundation/telos-amend#2]
- [ ] Determine fee structure
- [ ] Inline transfer to trailservice for fee coverage?
- [ ] Calculate section numbers on amendment
- [ ] Handle ties, no-vote ballots
- [ ] Quorum logic, vote thresholds
